name: playground
dependencies:
  - python>=3.8
  - pip
  - pip:
      - -r requirements.txt
      - -r src/test_service/requirements.txt
      - -r src/hurricane_service/requirements.txt
      - -r src/wildfire_service/requirements.txt
